command:
  - "sh"
  - "-c"
  - "npm install && cd client && npm install && npm run build && cd .. && npm start"

env:
  - name: NODE_ENV
    value: production
  - name: PORT
    value: "8080"
  - name: DATABASE_URL
    value: "{{secrets/maturity-assessment/LAKEBASE_DATABASE_URL}}"
  - name: SESSION_SECRET
    value: "{{secrets/maturity-assessment/SESSION_SECRET}}"

