command:
  - "sh"
  - "-c"
  - "npm install && cd client && npm install && npm run build && cd .. && npm start"

env:
  - name: NODE_ENV
    value: production
  - name: PORT
    value: "8080"
  - name: DATABASE_URL
    value: "postgresql://user:pass@host:5432/db"
  - name: SESSION_SECRET
    value: "your-secret-key-here"

